stages:
  - test

run-pytest:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --maxfail=1 --disable-warnings --html=report.html
  artifacts:
    paths:
      - report.html
      - allure-results
